In [35]:
import numpy as np

a = np.arange(0, 6)
arr = np.array([a, a+10, a+20, a+30, a+40, a+50])
print(arr, '\n')

# 주황색 [2, 3, 4]
print("주황색 :", arr[0, [2, 3, 4]], '\n')

# 빨강색 [2, 12, 22, 32, 42, 52]
print("빨강색 :", arr[[0, 1, 2, 3, 4, 5], 2], '\n')

# 초록색 [20, 22, 24], [40, 42, 44] (팬시)
print("초록색 :", arr[[2,4]][:,[0,2,4]], '\n')
# 마스킹 (masking)
mask = np.array([0,0,1,0,1,0],dtype=bool)
print("초록색 마스킹 :", arr[mask][:,[0,2,4]], '\n')

# 하늘색 [44, 45], [54, 55]
print("하늘색 :", arr[4:, 4:])


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]] 

주황색 : [2 3 4] 

빨강색 : [ 2 12 22 32 42 52] 

초록색 : [[20 22 24]
 [40 42 44]] 

초록색 마스킹 : [[20 22 24]
 [40 42 44]] 

하늘색 : [[44 45]
 [54 55]]
